### ISSUE TITLE
[EC22] - check relevance of this rule

### ISSUE THREAD

**Issue by Mester766** [green-code-initiative/ecoCode-php#23]
Hi, on my symfony project, we have many code smells coming from this rule and i wonder if she is relevant to php.

For example, we have issues coming from file_exists or filemtime which are definitely not basic operations.

On the other hand, calling a function which only do a basic mathematic operation is clearly a code smell.

So I wonder if there is a relevance for this rule or if it could be enhanced so it does not match on non basic operations.

Thanks for your reply,

**Comment by dedece35** [comment]
hi @Mester766 , thank you for issue.
clearly, we are missing PHP experts, and Symphony experts. 
Could you give some screenshots to prove it, please ?
You can also open a PR with improvments to change rule implémentation if you have some ideas. But maybe, you only want to delete this rule for php ... ?!
thank you.
regards.
David.

**Comment by dedece35** [comment]
Hi @Mester766 ,

I'm ok with, I think the discussion on the same rule for Java is also quite relevant for PHP : see https://github.com/green-code-initiative/ecoCode/pull/148 
I'm going to mark this rule as a rule to prove with measurement.
